// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// setParameter
bool setParameter(String name, String value);
RcppExport SEXP _jaspQmlR_setParameter(SEXP nameSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type name(nameSEXP);
    Rcpp::traits::input_parameter< String >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(setParameter(name, value));
    return rcpp_result_gen;
END_RCPP
}
// loadDataSet
void loadDataSet(Rcpp::List data);
RcppExport SEXP _jaspQmlR_loadDataSet(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type data(dataSEXP);
    loadDataSet(data);
    return R_NilValue;
END_RCPP
}
// loadQmlFileAndCheckOptions
String loadQmlFileAndCheckOptions(String qmlFile, String options, String version);
RcppExport SEXP _jaspQmlR_loadQmlFileAndCheckOptions(SEXP qmlFileSEXP, SEXP optionsSEXP, SEXP versionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type qmlFile(qmlFileSEXP);
    Rcpp::traits::input_parameter< String >::type options(optionsSEXP);
    Rcpp::traits::input_parameter< String >::type version(versionSEXP);
    rcpp_result_gen = Rcpp::wrap(loadQmlFileAndCheckOptions(qmlFile, options, version));
    return rcpp_result_gen;
END_RCPP
}
// generateModuleWrappers
String generateModuleWrappers(String modulePath);
RcppExport SEXP _jaspQmlR_generateModuleWrappers(SEXP modulePathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type modulePath(modulePathSEXP);
    rcpp_result_gen = Rcpp::wrap(generateModuleWrappers(modulePath));
    return rcpp_result_gen;
END_RCPP
}
// generateAnalysisWrapper
String generateAnalysisWrapper(String modulePath, String qmlFileName, String analysisName);
RcppExport SEXP _jaspQmlR_generateAnalysisWrapper(SEXP modulePathSEXP, SEXP qmlFileNameSEXP, SEXP analysisNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type modulePath(modulePathSEXP);
    Rcpp::traits::input_parameter< String >::type qmlFileName(qmlFileNameSEXP);
    Rcpp::traits::input_parameter< String >::type analysisName(analysisNameSEXP);
    rcpp_result_gen = Rcpp::wrap(generateAnalysisWrapper(modulePath, qmlFileName, analysisName));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_jaspQmlR_setParameter", (DL_FUNC) &_jaspQmlR_setParameter, 2},
    {"_jaspQmlR_loadDataSet", (DL_FUNC) &_jaspQmlR_loadDataSet, 1},
    {"_jaspQmlR_loadQmlFileAndCheckOptions", (DL_FUNC) &_jaspQmlR_loadQmlFileAndCheckOptions, 3},
    {"_jaspQmlR_generateModuleWrappers", (DL_FUNC) &_jaspQmlR_generateModuleWrappers, 1},
    {"_jaspQmlR_generateAnalysisWrapper", (DL_FUNC) &_jaspQmlR_generateAnalysisWrapper, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_jaspQmlR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
