// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// checkOptions
String checkOptions(String jsonValue);
RcppExport SEXP _checkOptions(SEXP jsonValueSEXP) {
BEGIN_RCPP
	Rcpp::RObject rcpp_result_gen;
	Rcpp::RNGScope rcpp_rngScope_gen;
	Rcpp::traits::input_parameter< String >::type jsonValue(jsonValueSEXP);
	rcpp_result_gen = Rcpp::wrap(checkOptions(jsonValue));
	return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
	{"_qmlR_checkOptions", (DL_FUNC) &_checkOptions, 1},
	{NULL, NULL, 0}
};

RcppExport void R_init_jaspQmlR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
