# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test <- function(data) {
    .Call(`_jaspQmlR_test`, data)
}

loadDataSet <- function(data) {
    invisible(.Call(`_jaspQmlR_loadDataSet`, data))
}

loadQmlFileAndCheckOptions <- function(qmlFile, options, version) {
    .Call(`_jaspQmlR_loadQmlFileAndCheckOptions`, qmlFile, options, version)
}

generateModuleWrappers <- function(modulePath) {
    .Call(`_jaspQmlR_generateModuleWrappers`, modulePath)
}

generateAnalysisWrapper <- function(modulePath, qmlFileName, analysisName) {
    .Call(`_jaspQmlR_generateAnalysisWrapper`, modulePath, qmlFileName, analysisName)
}

