# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
runQml <- function(qmlFilePath, options, data) {
    .Call(`_qmlR_runQml`, qmlFilePath, options, data)
}
