# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

setParameter <- function(name, value) {
    .Call(`_jaspQmlR_setParameter`, name, value)
}

loadDataSet <- function(data) {
    invisible(.Call(`_jaspQmlR_loadDataSet`, data))
}

loadQmlFileAndCheckOptions <- function(moduleName, analysisName, qmlFile, options, version) {
    .Call(`_jaspQmlR_loadQmlFileAndCheckOptions`, moduleName, analysisName, qmlFile, options, version)
}

generateModuleWrappers <- function(modulePath) {
    .Call(`_jaspQmlR_generateModuleWrappers`, modulePath)
}

generateAnalysisWrapper <- function(modulePath, qmlFileName, analysisName) {
    .Call(`_jaspQmlR_generateAnalysisWrapper`, modulePath, qmlFileName, analysisName)
}

